### ISSUE TITLE
raspberry pi4

### ISSUE THREAD

**Issue by notDavid** [Reeceeboii/Pi-CLI#8]
Hi there, should this run on a raspbery pi4? I get this error when running the setup:

```
$ picli setup
Please enter the IP address of your Pi-Hole: 127.0.0.1
Please enter the port that exposes the web interface (default 80): 80
Please enter your preferred data refresh rate in seconds (default 1s): 1
Enter API key (stored securely, not in a file): *****
2021/02/21 12:20:42 exec: "dbus-launch": executable file not found in $PATH
```

**Comment by Reeceeboii** [comment]
@notDavid What version of Raspbian are you running?

**Comment by notDavid** [comment]
```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```

I don't have a desktop environment installed btw.

**Comment by Reeceeboii** [comment]
Will do some investigation.

Issue seems to be coming from the keyring library that Pi-CLI is using. (Another instance of a failure in the same setup step from #9 )

Temporary workaround is running Pi-CLI on an another system that doesn't have the keyring issue and pointing at your Raspberry-Pi (as opposed to running it on the Pi directly and pointing it at itself). This would have the downside of having to open a port if you haven't already. Best I can offer for now until I (or someone else) have time to do some digging in the code.

I will likely end up implementing a storage fallback for if the keyring calls fail.

**Comment by notDavid** [comment]
> I will likely end up implementing a storage fallback for if the keyring calls fail.

Sounds like a good plan;
When storing the API key on the Pi itself, where Pi-Hole is also running, no extra security is needed anyway (as the api key is stored in the Pi-hole database file itself anyway which is also accessible.)

So i think a plain text config file to store the api key would already be sufficient.

**Comment by notDavid** [comment]
@Reeceeboii Thanks for the quick solution! :)
