### ISSUE TITLE
Keyring issue?

### ISSUE THREAD

**Issue by ciordia9** [Reeceeboii/Pi-CLI#9]
Pi4b / Raspbarian 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
Headless / No desktop env.

After configure I get:
2021/02/21 17:26:52 The name org.freedesktop.secrets was not provided by any .service files

Sleuthing around it seems to be a keyring issue but I have keyring installed (https://pypi.org/project/keyring/), many say to install gnome-keyring but that bloats a tremendous amount. Do you know another way through this?

**Comment by Reeceeboii** [comment]
Looks a lot like #8 . This keyring library is causing a bit of hassle. Will need to do some investigation. Thank you for bringing this to my attention.
